"""add variation_id to cart_items

Revision ID: 078921da2f16
Revises: 6dbad277ce68
Create Date: 2025-10-19 22:13:31.951875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078921da2f16'
down_revision: Union[str, Sequence[str], None] = '6dbad277ce68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('variation_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('_user_product_uc'), 'cart_items', type_='unique')
    op.create_unique_constraint('_user_product_variation_uc', 'cart_items', ['user_id', 'product_id', 'variation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_product_variation_uc', 'cart_items', type_='unique')
    op.create_unique_constraint(op.f('_user_product_uc'), 'cart_items', ['user_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('cart_items', 'variation_id')
    # ### end Alembic commands ###
