"""add channel posts table

Revision ID: 11879e8f729e
Revises: b0d30b90ab80
Create Date: 2025-10-18 22:28:11.824821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11879e8f729e'
down_revision: Union[str, Sequence[str], None] = 'b0d30b90ab80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('buttons_json', sa.Text(), nullable=True),
    sa.Column('channel_message_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_posts_channel_message_id'), 'channel_posts', ['channel_message_id'], unique=False)
    op.create_index(op.f('ix_channel_posts_id'), 'channel_posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_posts_id'), table_name='channel_posts')
    op.drop_index(op.f('ix_channel_posts_channel_message_id'), table_name='channel_posts')
    op.drop_table('channel_posts')
    # ### end Alembic commands ###
