"""add dialogue and dialogue message tables

Revision ID: 46517af9cca9
Revises: ad62694e6929
Create Date: 2025-10-19 15:45:38.196306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46517af9cca9'
down_revision: Union[str, Sequence[str], None] = 'ad62694e6929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_snippet', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogues_id'), 'dialogues', ['id'], unique=False)
    op.create_index(op.f('ix_dialogues_status'), 'dialogues', ['status'], unique=False)
    op.create_index(op.f('ix_dialogues_user_id'), 'dialogues', ['user_id'], unique=False)
    op.create_table('dialogue_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialogue_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dialogue_id'], ['dialogues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogue_messages_dialogue_id'), 'dialogue_messages', ['dialogue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialogue_messages_dialogue_id'), table_name='dialogue_messages')
    op.drop_table('dialogue_messages')
    op.drop_index(op.f('ix_dialogues_user_id'), table_name='dialogues')
    op.drop_index(op.f('ix_dialogues_status'), table_name='dialogues')
    op.drop_index(op.f('ix_dialogues_id'), table_name='dialogues')
    op.drop_table('dialogues')
    # ### end Alembic commands ###
