"""change channel post to have a single button

Revision ID: 566374d845a9
Revises: 706cd4f22b59
Create Date: 2025-10-19 13:11:27.123721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566374d845a9'
down_revision: Union[str, Sequence[str], None] = '706cd4f22b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_posts', sa.Column('button_text', sa.String(), nullable=True))
    op.add_column('channel_posts', sa.Column('button_url', sa.String(), nullable=True))
    op.drop_column('channel_posts', 'button_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_posts', sa.Column('button_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('channel_posts', 'button_url')
    op.drop_column('channel_posts', 'button_text')
    # ### end Alembic commands ###
