"""add media fields to dialogue messages

Revision ID: 6dbad277ce68
Revises: 46517af9cca9
Create Date: 2025-10-19 16:45:54.724675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dbad277ce68'
down_revision: Union[str, Sequence[str], None] = '46517af9cca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialogue_messages', sa.Column('media_type', sa.String(length=50), nullable=True))
    op.add_column('dialogue_messages', sa.Column('media_url', sa.String(), nullable=True))
    op.add_column('dialogue_messages', sa.Column('file_name', sa.String(), nullable=True))
    op.alter_column('dialogue_messages', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dialogue_messages', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('dialogue_messages', 'file_name')
    op.drop_column('dialogue_messages', 'media_url')
    op.drop_column('dialogue_messages', 'media_type')
    # ### end Alembic commands ###
