"""change channel post to have a single button

Revision ID: 706cd4f22b59
Revises: 11879e8f729e
Create Date: 2025-10-18 23:05:04.681127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706cd4f22b59'
down_revision: Union[str, Sequence[str], None] = '11879e8f729e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_posts', sa.Column('button_json', sa.Text(), nullable=True))
    op.drop_column('channel_posts', 'buttons_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_posts', sa.Column('buttons_json', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('channel_posts', 'button_json')
    # ### end Alembic commands ###
