"""Add image_url to notifications

Revision ID: 7fb38abcb9e5
Revises: 4102b968fcb2
Create Date: 2025-09-19 17:22:46.524652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb38abcb9e5'
down_revision: Union[str, Sequence[str], None] = '4102b968fcb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'image_url')
    # ### end Alembic commands ###
