"""Create notifications table

Revision ID: 87d3d284a214
Revises: c1f7a97a0e09
Create Date: 2025-09-14 13:18:29.303127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d3d284a214'
down_revision: Union[str, Sequence[str], None] = 'c1f7a97a0e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    # ### end Alembic commands ###
