"""refactor channel posts for titles and media groups

Revision ID: 9a0cd3f04382
Revises: 566374d845a9
Create Date: 2025-10-19 13:26:07.140931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0cd3f04382'
down_revision: Union[str, Sequence[str], None] = '566374d845a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_posts', sa.Column('title', sa.String(), nullable=True))
    op.add_column('channel_posts', sa.Column('media_urls_json', sa.Text(), nullable=True))
    op.add_column('channel_posts', sa.Column('button_json', sa.Text(), nullable=True))
    op.drop_column('channel_posts', 'button_url')
    op.drop_column('channel_posts', 'button_text')
    op.drop_column('channel_posts', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_posts', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('channel_posts', sa.Column('button_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('channel_posts', sa.Column('button_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('channel_posts', 'button_json')
    op.drop_column('channel_posts', 'media_urls_json')
    op.drop_column('channel_posts', 'title')
    # ### end Alembic commands ###
