"""Add created_at to users and server defaults

Revision ID: a44746bce6e6
Revises: 5b6c4c8e54c3
Create Date: 2025-09-15 17:24:39.528979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44746bce6e6'
down_revision: Union[str, Sequence[str], None] = '5b6c4c8e54c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
