"""store all message ids for channel posts

Revision ID: a7ae376dc38f
Revises: 9a0cd3f04382
Create Date: 2025-10-19 14:35:04.641843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7ae376dc38f'
down_revision: Union[str, Sequence[str], None] = '9a0cd3f04382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_posts', sa.Column('channel_message_ids_json', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_channel_posts_channel_message_id'), table_name='channel_posts')
    op.drop_column('channel_posts', 'channel_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_posts', sa.Column('channel_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_channel_posts_channel_message_id'), 'channel_posts', ['channel_message_id'], unique=False)
    op.drop_column('channel_posts', 'channel_message_ids_json')
    # ### end Alembic commands ###
