"""Add action_url column to notifications table

Revision ID: aa511a53dc4e
Revises: 87d3d284a214
Create Date: 2025-09-14 22:42:30.498534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa511a53dc4e'
down_revision: Union[str, Sequence[str], None] = '87d3d284a214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('action_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'action_url')
    # ### end Alembic commands ###
