"""add advanced broadcast features and recipients tracking

Revision ID: ab1b2a61ea96
Revises: 6b9f27425422
Create Date: 2025-10-18 13:15:56.909961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1b2a61ea96'
down_revision: Union[str, Sequence[str], None] = '6b9f27425422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_recipients_broadcast_id'), 'broadcast_recipients', ['broadcast_id'], unique=False)
    op.add_column('broadcasts', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('broadcasts', sa.Column('button_text', sa.String(), nullable=True))
    op.add_column('broadcasts', sa.Column('button_url', sa.String(), nullable=True))
    op.add_column('broadcasts', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_broadcasts_status'), 'broadcasts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broadcasts_status'), table_name='broadcasts')
    op.drop_column('broadcasts', 'scheduled_at')
    op.drop_column('broadcasts', 'button_url')
    op.drop_column('broadcasts', 'button_text')
    op.drop_column('broadcasts', 'image_url')
    op.drop_index(op.f('ix_broadcast_recipients_broadcast_id'), table_name='broadcast_recipients')
    op.drop_table('broadcast_recipients')
    # ### end Alembic commands ###
