"""add related_transaction_id

Revision ID: b0d30b90ab80
Revises: ab1b2a61ea96
Create Date: 2025-10-18 21:01:34.249493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d30b90ab80'
down_revision: Union[str, Sequence[str], None] = 'ab1b2a61ea96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loyalty_transactions', sa.Column('related_transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loyalty_transactions', 'loyalty_transactions', ['related_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loyalty_transactions', type_='foreignkey')
    op.drop_column('loyalty_transactions', 'related_transaction_id')
    # ### end Alembic commands ###
