"""Add broadcasts photo

Revision ID: b43cc937b6f1
Revises: b5f61add8d78
Create Date: 2025-09-07 23:30:47.543371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43cc937b6f1'
down_revision: Union[str, Sequence[str], None] = 'b5f61add8d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broadcasts', sa.Column('photo_file_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcasts', 'photo_file_id')
    # ### end Alembic commands ###
