"""Add loyalty system and user levels

Revision ID: c588b651786b
Revises: ea28b419d0e7
Create Date: 2025-09-07 08:23:15.318565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c588b651786b'
down_revision: Union[str, Sequence[str], None] = 'ea28b419d0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('order_id_wc', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_transactions_id'), 'loyalty_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_loyalty_transactions_order_id_wc'), 'loyalty_transactions', ['order_id_wc'], unique=False)
    op.add_column('users', sa.Column('level', sa.String(), nullable=False, server_default='bronze'))
    op.add_column('users', sa.Column('bot_accessible', sa.Boolean(), nullable=True, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bot_accessible')
    op.drop_column('users', 'level')
    op.drop_index(op.f('ix_loyalty_transactions_order_id_wc'), table_name='loyalty_transactions')
    op.drop_index(op.f('ix_loyalty_transactions_id'), table_name='loyalty_transactions')
    op.drop_table('loyalty_transactions')
    # ### end Alembic commands ###
